<a href="https://colab.research.google.com/github/Skakarla2023/numpy-beginner-projects/blob/main/numpy-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY in Python**

## **Creating arrays using numpy**

In [ ]:
import numpy as np

In [ ]:
# 1 dimensional array
a=np.array([1,2,3])

a

array([1, 2, 3])

In [ ]:
# 2 dimensional array
b=np.array([[1,2],[3,4]])

b

array([[1, 2],
       [3, 4]])

In [ ]:
# 3 dimensional array
c=np.array([[[1],[2]],[[3],[4]]])

c

array([[[1],
        [2]],

       [[3],
        [4]]])

## **Array Properties**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Datatype:",arr.dtype)
print("Dimensions:",arr.ndim)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Datatype: int64
Dimensions: 2


### **Array Creation Methods**

In [ ]:
# creating an array of zeroes
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# creating an array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# creating an Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# creating all same elements
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
# generating an evenly space array linspace(start,stop,number_of_elements/numbers)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
# generates equally spaced numbers between (0,1]
np.random.rand(3,3)

array([[0.14520529, 0.82843421, 0.81313743],
       [0.29022068, 0.95138522, 0.56867452],
       [0.92683934, 0.03180258, 0.52936692]])

In [ ]:
np.random.randint(1,10,(3,3))

array([[9, 6, 1],
       [1, 1, 1],
       [9, 8, 1]])

## **Array Indexing and slicing**

In [ ]:
arr=np.array([10,20,30,40,50])

print(arr[2:4])
print(arr[1:2])
print(arr[2])

[30 40]
[20]
30


In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat[:,1])
print(mat[1:4])

[2 5]
[[4 5 6]]


## **Array Operations**

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)
print(a**b)
print(np.sqrt(a))

[5 7 9]
[ 4 10 18]
[  1  32 729]
[1.         1.41421356 1.73205081]


### **Matrix operations**

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.transpose(a))

[[1 3]
 [2 4]]


In [ ]:
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(np.linalg.det(a))

-2.0000000000000004


In [ ]:
print(a.dot(b))

[[19 22]
 [43 50]]


## **Boolean indexing and conditions**

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

[4 5]


## **Iteration and reshape**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
for row in a:
  print(row)

[1 2 3]
[4 5 6]


In [ ]:
arr=np.array([[[1],[2]],[[3],[4]]])
print(arr.flatten())

[1 2 3 4]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(b.reshape(-1,3))

[[1 2 3]
 [4 5 6]]


## **Aggregate functions**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.mean(a))
print(np.min(a),np.max(a))

21
3.5
1 6


## **Numpy Problem Solving Questions**

### 1.Replace all odd numbers with -1 in an array from 0 to 20

In [ ]:
arr = np.arange(20)
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


### 2.Create 4X4 Identity matrix and square it

In [ ]:
arr = np.eye(4)
print(np.matmul(arr,arr))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 3.Find maximum in each row of matrix

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr,axis=1))

[3 6]


### 4.Generate 4X5 array with random integer (10 to 99) and find even numbers

In [ ]:
arr = np.random.randint(10,100,(4,5))
print(arr[arr%2==0])

[76 66 28 52 26 72 74 82]


### 5.Create an array and compute cummulative sum

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21])

### 6.Find indices where elements are greater than 25

In [ ]:
arr = np.array([10,25,30,6,60])
arr1=np.where(arr>25)
print(arr1)

(array([2, 4]),)


### 7.Create 3X3 matrix find diagonal elments

In [ ]:
d=np.array([1,2,3])
np.diag(d)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 8.Generate 2D array & reverse each row

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4]])

### 9. Count non-zero elements in an array

In [ ]:
import numpy as np
arr = np.array([0,2,3,4,5,6])
np.count_nonzero(arr)

5

# **Numpy Datatypes**

In [ ]:
import numpy as np

a1=np.array([1,2,3,4,5])
a2=np.array(["a","b","c","d"])
a3=np.array(["abc","bcd","cde"])

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
<U1
<U3
