<a href="https://colab.research.google.com/github/Skakarla2023/Numpy_Beginner_Projects/blob/main/numpy_in_stocks_pdf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Stock-Market Analysis in numpy**

In [ ]:
import numpy as np

In [ ]:
stock_names=['A','B','C']

In [ ]:
import numpy as np
prices = np.array([
    [120, 230, 340],
    [125, 235, 330],
    [123, 240, 335],
    [128, 238, 342],
    [127, 243, 350],
    [130, 248, 345],
    [132, 250, 355]
])

In [ ]:
avg_prices=np.mean(prices,axis=0)
avg_prices

array([126.42857143, 240.57142857, 342.42857143])

In [ ]:
daily_returns = (prices[1:]-prices[:-1])/prices[:-1] * 100
daily_returns

array([[ 4.16666667,  2.17391304, -2.94117647],
       [-1.6       ,  2.12765957,  1.51515152],
       [ 4.06504065, -0.83333333,  2.08955224],
       [-0.78125   ,  2.10084034,  2.33918129],
       [ 2.36220472,  2.05761317, -1.42857143],
       [ 1.53846154,  0.80645161,  2.89855072]])

In [ ]:
std_deviation=np.std(prices,axis=0)
std_deviation

array([3.81190402, 6.54341857, 7.90763   ])

In [ ]:
for i,name in enumerate(stock_names):
  print(f"\n{name} Analysis:")
  print(f"Average Price:₹{avg_prices[i]:.3f}")
  print(f"Standard Deviations:{std_deviation[i]:.3f}")


A Analysis:
Average Price:₹126.429
Standard Deviations:3.812

B Analysis:
Average Price:₹240.571
Standard Deviations:6.543

C Analysis:
Average Price:₹342.429
Standard Deviations:7.908


# **Daily Prices for 3 Stocks**

### ✅ 1.1 Generate Daily Price Data

In [ ]:
np.random.seed(42)
prices = np.random.randint(100,300,size=(7,3))
stock_names=['Stock A','Stock B','Stock C']
days = [f'Day {i+1}' for i in range(7)]

In [ ]:
print("📊 Daily Stock Prices:")
for i, day in enumerate(days):
  print(f"{day}: {dict(zip(stock_names, prices[i]))}")

📊 Daily Stock Prices:
Day 1: {'Stock A': np.int64(202), 'Stock B': np.int64(279), 'Stock C': np.int64(192)}
Day 2: {'Stock A': np.int64(114), 'Stock B': np.int64(206), 'Stock C': np.int64(171)}
Day 3: {'Stock A': np.int64(288), 'Stock B': np.int64(120), 'Stock C': np.int64(202)}
Day 4: {'Stock A': np.int64(221), 'Stock B': np.int64(174), 'Stock C': np.int64(187)}
Day 5: {'Stock A': np.int64(216), 'Stock B': np.int64(199), 'Stock C': np.int64(203)}
Day 6: {'Stock A': np.int64(251), 'Stock B': np.int64(230), 'Stock C': np.int64(249)}
Day 7: {'Stock A': np.int64(152), 'Stock B': np.int64(101), 'Stock C': np.int64(187)}


### ✅ 1.2 Daily Returns (% Change from Previous Day)

In [ ]:
# Daily return=((today-yesterday)/yesterday)*100
daily_returns=((prices[1:]-prices[:-1])/prices[:-1])*100
print("\n📈 Daily Returns(%):")
for i,day in enumerate(days[1:],start=1):
  returns = dict(zip(stock_names,daily_returns[i-1].round(2)))
  print(f"{day} return: {returns}")


📈 Daily Returns(%):
Day 2 return: {'Stock A': np.float64(-43.56), 'Stock B': np.float64(-26.16), 'Stock C': np.float64(-10.94)}
Day 3 return: {'Stock A': np.float64(152.63), 'Stock B': np.float64(-41.75), 'Stock C': np.float64(18.13)}
Day 4 return: {'Stock A': np.float64(-23.26), 'Stock B': np.float64(45.0), 'Stock C': np.float64(-7.43)}
Day 5 return: {'Stock A': np.float64(-2.26), 'Stock B': np.float64(14.37), 'Stock C': np.float64(8.56)}
Day 6 return: {'Stock A': np.float64(16.2), 'Stock B': np.float64(15.58), 'Stock C': np.float64(22.66)}
Day 7 return: {'Stock A': np.float64(-39.44), 'Stock B': np.float64(-56.09), 'Stock C': np.float64(-24.9)}


### ✅ 1.3 Individual Stock Weekly Analysis

In [ ]:
average_price = np.mean(prices,axis=0)
max_price = np.max(prices,axis=0)
min_price = np.min(prices,axis=0)
standard_deviation = np.std(prices,axis=0)

print("\n Weekly analysis for each stock:")
for i,name in enumerate(stock_names):
  print(f"\n{name}")
  print(f" Average Price:₹{average_price[i]:.2f}")
  print(f" Maximum Price:₹{max_price[i]:.2f}")
  print(f" Minimum Price:₹{min_price[i]:.2f}")
  print(f" Standard Deviation:₹{standard_deviation[i]:.2f}")


 Weekly analysis for each stock:

Stock A
 Average Price:₹206.29
 Maximum Price:₹288.00
 Minimum Price:₹114.00
 Standard Deviation:₹54.08

Stock B
 Average Price:₹187.00
 Maximum Price:₹279.00
 Minimum Price:₹101.00
 Standard Deviation:₹57.16

Stock C
 Average Price:₹198.71
 Maximum Price:₹249.00
 Minimum Price:₹171.00
 Standard Deviation:₹22.82


### ✅ 1.4 Most Gained / Lost Stock Over the Week

In [ ]:
overall_returns = (prices[-1] - prices[0]) / prices[0] * 100
most_gained = np.argmax(overall_returns)
# argmax returns the maximum value in an array
most_lost = np.argmin(overall_returns)
# argmin returns the minimum value in an array
print(f"\n Performance Summary:")
print(f" Most Gained: {stock_names[most_gained]} ({overall_returns[most_gained]})")
print(f" Most Lost : {stock_names[most_lost]} ({overall_returns[most_lost]})")


 Performance Summary:
 Most Gained: Stock C (-2.604166666666667)
 Most Lost : Stock B (-63.799283154121866)


# **PART 2 Hourly prices(7 days x 6 hours x 3 stocks)**

### ✅ 2.1 Generate Hourly Price List

In [ ]:
import numpy as np

In [ ]:
# 7 days x 6 hours(9AM-2PM) x 3 stocks
prices_hourly = np.random.randint(100,300,(7,6,3))
hours = ["9AM","10AM","11AM","12PM","1PM","2PM"]

print("\nDay 1 Hourly Prices:\n")
for i,hour in enumerate(hours):
  hourly_prices_for_display = [int(price) for price in prices_hourly[0][i]]
  print(f"{hour} :{dict(zip(stock_names,hourly_prices_for_display))}")


Day 1 Hourly Prices:

9AM :{'Stock A': 200, 'Stock B': 122, 'Stock C': 109}
10AM :{'Stock A': 168, 'Stock B': 199, 'Stock C': 133}
11AM :{'Stock A': 279, 'Stock B': 237, 'Stock C': 246}
12PM :{'Stock A': 285, 'Stock B': 195, 'Stock C': 100}
1PM :{'Stock A': 168, 'Stock B': 103, 'Stock C': 115}
2PM :{'Stock A': 123, 'Stock B': 179, 'Stock C': 101}


### Daily Average Price(from Hourly data)

In [ ]:
daily_avg_hourly = np.mean(prices_hourly,axis=1)
# When axis=0, the average is calculated down the rows for each column
# When axis=1, the average is calculated across the columns for each row

print(f"\n Daily averages from hourly data:")
for i,day in enumerate(days):
  avg_daily_hourly=[int(p) for p in daily_avg_hourly[i]]
  print(f"{day}: {dict(zip(stock_names,avg_daily_hourly))}")


 Daily averages from hourly data:
Day 1: {'Stock A': 203, 'Stock B': 172, 'Stock C': 134}
Day 2: {'Stock A': 239, 'Stock B': 228, 'Stock C': 206}
Day 3: {'Stock A': 198, 'Stock B': 154, 'Stock C': 193}
Day 4: {'Stock A': 245, 'Stock B': 202, 'Stock C': 229}
Day 5: {'Stock A': 170, 'Stock B': 184, 'Stock C': 194}
Day 6: {'Stock A': 231, 'Stock B': 171, 'Stock C': 224}
Day 7: {'Stock A': 208, 'Stock B': 235, 'Stock C': 191}


### Hourly Average across all 7 Days